# Generated by Django 3.2.7 on 2022-10-14 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('match_round', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_option', models.IntegerField(choices=[(0, 'Big Home'), (1, 'Small Home'), (2, 'Draw'), (3, 'Big Away'), (4, 'Small Away')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby_tipping.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
