# Generated by Django 3.2.7 on 2022-10-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_tipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='pick_option',
            new_name='pick_option_integer',
        ),
    ]
