# Generated by Django 3.2.7 on 2022-10-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_tipping', '0002_rename_pick_option_pick_pick_option_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_sports_id',
            field=models.IntegerField(null=True),
        ),
    ]
