# Generated by Django 3.2.7 on 2022-10-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_tipping', '0006_alter_tipper_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_api_sports_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_api_sports_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='pick_option_integer',
            field=models.IntegerField(choices=[(0, 'Big Home'), (1, 'Small Home'), (2, 'Draw'), (3, 'Small Away'), (4, 'Big Away')]),
        ),
    ]
